global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'go_market'
    static_configs:
      - targets: ['host.docker.internal:8080']
    metrics_path: '/api/v1/metrics'